Event Page added
iiitkottayam/Dhruva pull request #36
Opened 2021-09-07 07:25 UTC by bindalsarthak03

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

# Browsers Tested on?

- [X] Chrome
- [X] Firefox
- [X] Edge

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have checked the responsiveness of the component I built
- [X] My changes generate no new warnings

2021-09-07 13:31 UTC, faiz-hasan11 commented
- Link Navbar to your page
- In mobile screens cards should be aligned in a single column

2021-09-07 16:34 UTC, faiz-hasan11 commented
Development branch updated , take a pull and then work

2021-09-07 17:42 UTC, faiz-hasan11 requested changes, later dismissed
- In Mobile View Add some spaces between cards
- For iPad , make it a square grid of 2 rows and 2 columns

2021-09-09 06:18 UTC, joshi008 requested changes, later dismissed
- Allign event name, lorem ipsum, and register button more towards right. They are currently more left. 
![image](https://user-images.githubusercontent.com/54844760/132633104-c16810d0-2896-44a8-8a0f-982dc401400f.png)

- Event details is also too much left.

2021-09-10 05:39 UTC, starwiz-7 commented on styles/Orgnjdge.module.css
> +        width: 51%;
Remove width 51% here. It makes all cards show as a list.

2021-09-10 05:40 UTC, starwiz-7 commented on styles/Orgnjdge.module.css
> +        justify-content: center;
change justify-content to space-evenly

2021-09-10 05:57 UTC, starwiz-7 commented on components/Events/Card.jsx
> +import { TiSocialLinkedinCircular, TiSocialTwitterCircular, TiSocialFacebookCircular } from 'react-icons/ti'
Change the icons to FaLinkedin, FaTwitter, FaInstagram from react-icons/fa to maintain consistency as we have not used circular icons anywhere else.

2021-09-10 05:58 UTC, starwiz-7 commented on styles/Orgnjdge.module.css
> +    font-size: 50px;
Change font-size to 30px and subsequently in media queries

2021-09-10 06:04 UTC, starwiz-7 commented on styles/Orgnjdge.module.css
> +    font-size: 50px;
You can refer to this [codesandbox](https://codesandbox.io/s/cool-tree-omcx4) to look at how the above changes will perform!

2021-09-15 07:12 UTC, joshi008 commented
![image](https://user-images.githubusercontent.com/54844760/133387638-18cdbf66-b4cc-47f7-b8d9-b639587e559d.png)

2021-09-15 07:13 UTC, joshi008 commented
Also resolve the conflicts with the current devlopment branch

2021-09-15 11:06 UTC, faiz-hasan11 commented
Pull from the current dev branch and then push

2021-09-16 05:19 UTC, starwiz-7 approved these changes

2021-09-16 05:19 UTC, merged