speaker & attendees
iiitkottayam/Dhruva pull request #40
Opened 2021-09-08 17:37 UTC by RaiLokesh

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Browsers Tested on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked the responsiveness of the component I built
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2021-09-08 17:53 UTC, joshi008 requested changes
Try to remove these warnings as well:

![image](https://user-images.githubusercontent.com/54844760/132559743-3855584d-bace-437b-a2c8-ff7f350c1515.png)

2021-09-08 17:53 UTC, joshi008 commented on components/AttendeesSpeakers/attendes.js
> +                        <p className={styles.bl}>Put speakers at ease by making sure they're prepped and ready to go. Onboard them in the Green Room and communicate with them while they're on stage.<
Dont put single inverted commas ' . Instead use escape sequences.

2021-09-09 05:51 UTC, starwiz-7 commented on components/AttendeesSpeakers/attendes.js
> +                        <img data-aos="rotate-c" src="https://assets-global.website-files.com/5f8f45cead04af2f54abc938/611fc7ce31ecb97d9ed140ab_use_attendee.jpg" className={styles.hi}/>
Use Image tag from next/Image

2021-09-09 05:52 UTC, starwiz-7 commented on styles/attendees.module.css
> +@import url('https://fonts.googleapis.com/css2?family=Martel+Sans:wght@400;700;800&display=swap');
Do not use any new font, kindly use the font variable available in the global CSS file.

2021-09-09 10:39 UTC, starwiz-7 commented
1. Isn't responsive for screens around 750px (Complete image isn't visible)
2.  Scale down the image, currently, the size of the image is very large(Depends on our posters)

2021-09-12 09:33 UTC, starwiz-7 approved these changes

2021-09-12 09:34 UTC, starwiz-7 approved these changes

2021-09-12 09:35 UTC, merged