Added Design Changes
iiitkottayam/Dhruva pull request #68
Opened 2021-10-03 09:46 UTC by shashank1503-cipher

# Description
Changed the design of the organizer's section from cards to text in the Event Page, also connected the event page part to json. 

Fixes #65 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Browsers Tested on?

- [x] Chrome
- [x] Firefox
- [x] Edge

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked the responsiveness of the component I built
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-10-03 20:27 UTC, joshi008 requested changes
Kindly check the scrolling animation, it seems that the animation is changed and hence there is a delay in loading of images on scroll in event page.

2021-10-04 02:40 UTC, shashank1503-cipher commented
Made the images load faster.
Requesting for review

2021-10-04 13:16 UTC, starwiz-7 approved these changes

2021-10-09 18:19 UTC, joshi008 approved these changes

2021-10-09 18:19 UTC, merged